export { default as DashboardTabAdmin } from './DashboardTab'
export { default as OrderTabAdmin } from './OrderTab'
export { default as EmployeeTabAdmin } from './EmployeeTabAdmin'
export { default as ManagerTabAdmin } from './ManagerTabAdmin'
export { default as ProductTabAdmin } from './ProductTab'
export { default as AddCompanyTabAdmin } from './AddCompanyTab'
export { default as AddManagerTabAdmin } from './AddManagerTab'
export { default as AddEmployeeTabAdmin } from './AddEmployeeTab'
export { default as AllProductsTabAdmin } from './AllProductsTab'
export { default as AdminEditTab} from './AdminEdit'
